# Generated by Django 3.1.2 on 2020-10-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_answer_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='listing',
            field=models.BooleanField(default=False),
        ),
    ]
